### PR TITLE
[epmatsw] Add support for launching phantomJS on OSX

### PR DESCRIPTION
**Pull request by mitchhentges**
@epmatsw's fix for `phantomjs` on OSX, but without merge conflicts

### CODE REVIEW

**Comment by epmatsw** [comment]
Fwiw, I'm not sure that this code works. I ended up never really using it, and I'm sure there are unhandled edge cases.

**Comment by mitchhentges** [comment]
I double-checked on a Yosemite Mac, and it properly errors out when `phantomjs` doesn't exist, and (seems) to run when `phantomjs` does exist. Win!

**Comment by epmatsw** [comment]
Huh, well that's a lucky break. Good luck upkeeping this, I thought about forking but didn't want to commit. I think it'd be really cool going forward to try to emulate Karma's plugin API so that this could reuse their plugins for free. I tried using their exported launcher but it seemed to be pretty dependant on their dependency injection system.

**Comment by mitchhentges** [comment]
Whew, that seems like a taller order, hah :wink:. Feel free to create an issue, I might get bored one weekend!

**Comment by epmatsw** [comment]
Yeah, it definitely is. Just seems like that'd be a better way to maintain browser support. Just figured it might save you some work in the long run ;)

**Pull request merged**
